
#=================================================================================
# 容器相关设置
server:
  port: 9090
  context-path: /internal_trainserver


#=================================================================================
# spring 组件相关设置

spring:
  datasource:
#    url: jdbc:mysql://47.104.85.50:8085/springboot_demo?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf-8&characterSetResults=UTF-8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    url: jdbc:mysql://47.104.85.50:8085/misumi_train?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf-8&characterSetResults=UTF-8&autoReconnect=true&allowMultiQueries=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 6tfc7YGV8UHb


#=================================================================================
# 其他辅助框架相关配置

#=================================================================================
# 自定义参数相关配置

#=================================================================================